name: Test & Lint

on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true

      - name: Check code formatting
        run: |
          if [ -n "$(gofmt -s -l .)" ]; then
            echo "The following files are not formatted properly with gofmt:"
            gofmt -s -l .
            exit 1
          fi

      - name: Check go.mod tidy
        run: |
          go mod tidy
          git diff --exit-code

      - name: Run unit tests
        run: go test -race -v -coverprofile=coverage.txt -covermode=atomic ./...

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: "go.mod"
          check-latest: true
          cache: true

      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v8
        with:
          version: v2.12
